INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(1, 'Pablo', 'Perez', 'pablop@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(2, 'Luis', 'Garcia', 'luisg@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(3, 'Raquel', 'Muñoz', 'raquelm@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(4, 'Monica', 'Diaz', 'monicad@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(5, 'Javier', 'Diaz', 'javierd@gmail.com', '2022-08-28','unknown.jpg');

--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(6, 'Pablo', 'Jose', 'pablop@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(7, 'Luis', 'Pablo', 'luisg@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(8, 'Raquel', 'Muñoz', 'raquelm@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(9, 'Monica', 'Muñoz', 'monicad@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(10, 'Javier', 'Diaz', 'javierd@gmail.com', '2022-08-28','unknown.jpg');

--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(11, 'Javier', 'Perez', 'pablop@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(12, 'Luis', 'Perez', 'luisg@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(13, 'Monica', 'Muñoz', 'raquelm@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(14, 'Javier', 'Diaz', 'monicad@gmail.com', '2022-08-28','unknown.jpg');
--INSERT INTO clientes (id, nombre, apellido, email, create_at,foto) VALUES(15, 'Pablo', 'Diaz', 'javierd@gmail.com', '2022-08-28','unknown.jpg');

/* Creamos productos */

INSERT INTO productos (nombre, precio, create_at) VALUES ('Leche', 1.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Huevos', 2.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Pan de molde', 1.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Queso cheddar', 3.6, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Jamón cocido', 2.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Yogur natural', 1.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Arroz', 1.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Fideos', 1.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Atún en lata', 2.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Aceite de oliva', 3.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Aceitunas', 1.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Café', 3.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Té', 2.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Azúcar', 1.4, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Sal', 0.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Pimienta', 1.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Vinagre', 1.6, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Mostaza', 2.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Mayonesa', 2.4, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Ketchup', 2.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Salsa de soja', 2.7, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Salsa BBQ', 2.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Salsa de tomate', 1.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Patatas', 2.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cebollas', 1.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Zanahorias', 1.6, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Tomates', 2.4, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Pepinos', 1.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Lechuga', 1.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Espinacas', 2.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Pimientos', 2.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Calabacines', 1.7, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Brócoli', 2.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Coliflor', 2.4, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Ajo', 1.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Jengibre', 2.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Limones', 1.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Naranjas', 2.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Manzanas', 2.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Plátanos', 1.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Uvas', 2.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Sandía', 3.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Melón', 2.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Piña', 2.7, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Fresas', 3.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Melocotones', 2.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Nectarinas', 2.4, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Albaricoques', 2.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cerezas', 3.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Kiwi', 2.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Mango', 3.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Pera', 2.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Almendras', 4.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Nueces', 3.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Avellanas', 4.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Pistachos', 5.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cacahuetes', 2.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Chocolate negro', 3.6, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Chocolate con leche', 3.4, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Chocolate blanco', 3.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Galletas de chocolate', 2.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Galletas de vainilla', 1.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Bizcochos', 2.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cereales de maíz', 2.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cereales de avena', 2.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Barritas energéticas', 1.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Frutos secos mezclados', 3.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Gominolas', 1.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Chicles', 1.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Caramelos duros', 1.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Caramelos blandos', 1.7, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Mermelada', 2.4, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Mantequilla', 2.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Queso crema', 2.7, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Crema de cacahuete', 3.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Nutella', 3.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Miel', 2.6, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Sirope de arce', 4.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Leche condensada', 2.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Leche evaporada', 2.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Yogur de frutas', 1.7, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Yogur de sabores', 1.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Postre de chocolate', 2.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Flan', 2.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Natillas', 2.0, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Helado de vainilla', 3.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Helado de chocolate', 3.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Helado de fresa', 3.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Helado de limón', 3.0, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Helado de menta', 3.4, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Helado de pistacho', 3.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Refresco de cola', 1.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Refresco de naranja', 1.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Refresco de limón', 1.7, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Refresco de manzana', 1.9, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Zumo de naranja', 2.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Zumo de manzana', 2.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Zumo de piña', 2.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Agua mineral', 0.8, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Agua con gas', 1.1, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cerveza', 2.0, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Vino tinto', 3.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Vino blanco', 3.3, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Vino rosado', 3.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Whisky', 5.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Ginebra', 4.5, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Ron', 4.2, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Vodka', 4.0, NOW());

--INSERT INTO productos (nombre, precio, create_at) VALUES('Patatas 1kg', 1, NOW());
--INSERT INTO productos (nombre, precio, create_at) VALUES('Tomtates 1kg', 1, NOW());
--INSERT INTO productos (nombre, precio, create_at) VALUES('Naranjas 1kg', 1, NOW());
--INSERT INTO productos (nombre, precio, create_at) VALUES('Chocolate', 2, NOW());
--INSERT INTO productos (nombre, precio, create_at) VALUES('Lays', 1, NOW());
--INSERT INTO productos (nombre, precio, create_at) VALUES('Salsa de soja', 2, NOW());
--INSERT INTO productos (nombre, precio, create_at) VALUES('Vino', 2, NOW());

/* Creamos algunas facturas */
--INSERT INTO facturas (descripcion, observacion, cliente_id, create_at) VALUES('Factura compra dia 1', null, 1, NOW());
--INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(1, 1, 1);
--INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(2, 1, 4);
--INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(1, 1, 5);
--INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(1, 1, 7);

--INSERT INTO facturas (descripcion, observacion, cliente_id, create_at) VALUES('Factura compra dia 2', 'Me faltan lechugas', 1, NOW());
--INSERT INTO facturas_items (cantidad, factura_id, producto_id) VALUES(3, 2, 6);


